name: Publish Notion website to GitHub Pages

on:
  # Manual update only.
  workflow_dispatch:
  
permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout notionSnapshot
        uses: actions/checkout@v3
        with:
          repository: sueszli/notionSnapshot
          path: notionSnapshot
      - name: Checkout this repo
        uses: actions/checkout@v3
        with:
          path: pages_repo
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Download and install chromedriver
        run: sudo apt install chromium-chromedriver
      - name: Install notionSnapShot dependencies
        run: pip install -r notionSnapshot/requirements.txt
      - name: Run notionSnapshot
        run: |
          python3 notionSnapshot/notionsnapshot --dark-mode https://discreet-group-2ed.notion.site/Ruth-Alves-17c152b4e847804e891cfc4d84661b5a
      - name: Push to GitHub pages
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          GIT_DEPLOY_DIR=../snapshots/ruth-alves \
          GIT_DEPLOY_BRANCH=gh-pages \
          GIT_DEPLOY_REPO="https://${{ github.token }}@github.com/${{ github.repository }}.git" ./deploy.sh
        working-directory: pages_repo
